sonar.projectKey=task-management
sonar.projectName=Task Management
sonar.sources=frontend/src,user-service,task-service,notification-service
sonar.exclusions=**/node_modules/**,**/build/**,**/*.test.js
